version: '3.7'

services:
    web:
        image: repustate/dashboard:latest
        ports: 
            - 80:80
            - 443:443
        command: >
            /bin/bash -c '
            service nginx start &
            python3 manage.py collectstatic --noinput &
            python3 manage.py migrate &
            gunicorn  dashboard.wsgi --preload --workers=4 --timeout 300'
        depends_on: 
            - database
        env_file:
            - ./.env
        volumes: 
            - ./media_root:/var/www/media_root
            - ./certificates:/certificates
    database:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
        volumes: 
            - ./database:/var/lib/postgresql/data
        shm_size: 1g
        healthcheck:
            test: pg_isready -U postgres
            interval: 10s
            timeout: 3s
            retries: 3
    redis:
        image: redis
        healthcheck:
            test: redis-cli ping
            interval: 10s
            timeout: 3s
            retries: 3
    celery:
        image: repustate/dashboard:latest
        command: >
            /bin/bash -c '
            sleep 3;
            celery -A dashboard.celery worker'
        depends_on: 
            - redis
    flower:
        image: repustate/dashboard:latest
        command: >
            /bin/bash -c '
            sleep 3;
            flower -A dashboard'
