version: '3.7'

services:
    web:
        image: repustate/dashboard:latest
        ports: 
            - 80:80
            - 8000:8000
        command: >
            /bin/bash -c '
            service nginx start &
            python3 manage.py collectstatic --noinput &
            python3 manage.py migrate &
            python3 scripts/twitter_search_v1.py &
            celery -A dashboard.celery worker &
            flower -A dashboard flower --basic-auth=admin:admin &
            gunicorn dashboard.wsgi --preload --workers=4 --timeout 300'
        volumes: 
            - ./media_root:/var/www/media_root
            - ./docker/nginx-test.conf:/etc/nginx/sites-available/default
            - ./firebase-credentials.json:/firebase-credentials.json
        depends_on: 
            database:
                condition: service_healthy
        env_file: 
            - ./.env
    database:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: example
        env_file: 
            - ./.env
        ports:
            - 5432:5432
        volumes: 
            - ./database:/var/lib/postgresql/data
        shm_size: 1g
        healthcheck:
            test: pg_isready -U postgres
            interval: 10s
            timeout: 3s
            retries: 3
    redis:
        image: redis
        healthcheck:
            test: redis-cli ping
            interval: 10s
            timeout: 3s
            retries: 3
#    celery:
#        image: repustate/dashboard:latest
#        command: >
#            /bin/bash -c '
#            sleep 3;
#            '
#        depends_on: 
#            redis:
#                condition: service_healthy
#    flower:
#        image: repustate/dashboard:latest
#        command: >
#            /bin/bash -c '
#            sleep 3;
#            flower -A dashboard --basic-auth=admin:admin'
