version: '3.7'

services:
    web:
        image: juanpulydo/dashboard
        ports: 
            - 8080:80
            - 8000:8000
        command: >
            /bin/bash -c '
            service nginx start &&
            gunicorn  dashboard.wsgi --preload --log-level=DEBUG --workers=4 --timeout 300'
    database:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
        volumes: 
            - ./database:/var/lib/postgresql/data
        shm_size: 1g
    redis:
        image: redis
    celery:
        image: juanpulydo/dashboard
        command: >
            /bin/bash -c '
            sleep 3;
            celery -A dashboard.celery worker'
    flower:
        image: juanpulydo/dashboard
        command: >
            /bin/bash -c '
            sleep 3;
            flower -A dashboard'
