#!/bin/bash
 
NAME="repustate_dashboard"                                    # Name of the application
USER=ubuntu                                             # the user to run as
GROUP=ubuntu                                        # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
  
echo "Starting $NAME as `whoami`"

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
gunicorn dashboard.wsgi \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER \
--group=$GROUP \
--log-level=error \
--error-log=/tmp/gunicorn_dashboard \
--bind=127.0.0.1:8001
