# Generated by Django 3.0.8 on 2020-08-01 02:33

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('text', models.TextField()),
                ('sentiment', models.FloatField(default=0)),
                ('entities', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('aspects', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
                ('language', models.CharField(choices=[('ar', 'Arabic (العربية)'), ('zh', 'Chinese (中文)'), ('da', 'Danish (Dansk)'), ('nl', 'Dutch (Nederlands)'), ('en', 'English'), ('fi', 'Finnish (Suomi)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('he', 'Hebrew (עִברִית)'), ('it', 'Italian (Italiano)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('no', 'Norwegian (Norsk)'), ('pl', 'Polish (Polski)'), ('pt', 'Portuguese (Português)'), ('ru', 'Russian (русский)'), ('es', 'Spanish (Español)'), ('sv', 'Swedish (Svenska)'), ('tr', 'Turkish (Türk)'), ('th', 'Thai (ไทย)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('ur', 'Urdu (اردو)')], default='en', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
    ]
