# Generated by Django 2.0.5 on 2020-08-07 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200807_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect',
            name='sentiment_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None),
        ),
    ]
