# Generated by Django 2.0.5 on 2020-08-10 16:07

import data.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200807_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=data.models.default_field),
        ),
    ]
