# Generated by Django 3.0.8 on 2020-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200807_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=80)),
                ('chart_size', models.IntegerField()),
                ('project', models.ManyToManyField(to='data.Project')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='classifications',
            field=models.ManyToManyField(to='data.Classification'),
        ),
    ]
