# Generated by Django 3.0.8 on 2020-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200811_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='entities',
            field=models.ManyToManyField(to='data.Entity'),
        ),
    ]
