# Generated by Django 3.0.8 on 2020-08-11 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200811_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Data')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Emotion')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Entity')),
            ],
        ),
    ]
