# Generated by Django 3.0.8 on 2020-08-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_emotion_emotionalentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emotion',
            name='label',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Source'),
        ),
    ]
