# Generated by Django 2.0.5 on 2020-08-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200810_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chart',
        ),
    ]
