# Generated by Django 3.0.8 on 2020-08-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200812_1618'),
        ('data', '0008_auto_20200812_1505'),
    ]

    operations = [
    ]
