# Generated by Django 3.0.8 on 2020-08-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_merge_20200812_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='keywords',
        ),
    ]
