# Generated by Django 3.0.8 on 2020-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200812_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.AddField(
            model_name='project',
            name='charts',
            field=models.ManyToManyField(to='data.ChartType'),
        ),
    ]
