# Generated by Django 3.1 on 2020-09-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200818_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterField(
            model_name='aspect',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='aspect',
            name='sentiment',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='aspect',
            name='topic',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='label',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='data',
            name='sentiment',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
