# Generated by Django 3.0.7 on 2020-09-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200903_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttype',
            name='load_async',
            field=models.BooleanField(default=False),
        ),
    ]
