# Generated by Django 3.1 on 2020-09-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_charttype_load_async'),
        ('data', '0013_auto_20200903_0125'),
    ]

    operations = [
    ]
