# Generated by Django 3.0.8 on 2020-09-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_twittersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='twittersearch',
            options={'verbose_name_plural': 'Twitter Searches'},
        ),
        migrations.AddField(
            model_name='twittersearch',
            name='entities',
            field=models.BooleanField(default=False, help_text='Do you want to detect entities?'),
        ),
        migrations.AlterField(
            model_name='twittersearch',
            name='completed',
            field=models.BooleanField(default=False, help_text='Set automatically'),
        ),
        migrations.AddField(
            model_name='twittersearch',
            name='aspect',
            field=models.ForeignKey(default=None, help_text='Which aspect model to use? (optional)', on_delete=django.db.models.deletion.CASCADE, to='data.AspectType'),
            preserve_default=False,
        ),
    ]
