# Generated by Django 3.0.8 on 2020-09-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200930_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittersearch',
            name='aspect',
            field=models.ForeignKey(blank=True, default=None, help_text='Which aspect model to use? (optional)', on_delete=django.db.models.deletion.CASCADE, to='data.AspectType'),
        ),
    ]
