# Generated by Django 3.0.8 on 2020-09-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20200930_1802'),
        ('data', '0015_merge_20200903_0209'),
    ]

    operations = [
    ]
