# Generated by Django 3.0.8 on 2020-10-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20201001_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittersearch',
            name='aspect',
            field=models.ForeignKey(blank=True, default=None, help_text='Which aspect model to use? (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.AspectType'),
        ),
    ]
