# Generated by Django 3.0.8 on 2020-11-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20201023_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='data',
            name='weighted_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
