# Generated by Django 3.0.8 on 2020-11-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20201023_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='adjectives',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
