# Generated by Django 3.0.8 on 2020-11-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20201113_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='adjectives',
            new_name='label',
        ),
    ]
