# Generated by Django 3.0.8 on 2020-11-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20201109_1940'),
        ('data', '0024_auto_20201114_1001'),
    ]

    operations = [
    ]
