# Generated by Django 3.0.8 on 2020-11-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_merge_20201114_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='location',
        ),
    ]
