# Generated by Django 3.0.8 on 2020-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_remove_data_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.CharField(default='US', max_length=2),
        ),
    ]
