# Generated by Django 3.0.8 on 2020-11-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_data_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='label',
            new_name='adjective',
        ),
    ]
