# Generated by Django 3.0.8 on 2020-11-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20201115_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='adjective',
            new_name='label',
        ),
    ]
