# Generated by Django 3.0.8 on 2020-11-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20201115_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='data',
            name='location',
        ),
    ]
