# Generated by Django 3.0.8 on 2020-11-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20201116_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='frequency',
        ),
    ]
