# Generated by Django 3.0.8 on 2020-11-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_remove_comment_frequency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Keyword',
        ),
    ]
