# Generated by Django 3.0.8 on 2020-12-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20201202_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryNew',
            new_name='Country',
        ),
    ]
