# Generated by Django 3.0.8 on 2020-12-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20201202_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='adjectives',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='label',
            field=models.CharField(default='empty', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmotionalEntity',
        ),
    ]
