# Generated by Django 3.0.8 on 2020-12-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20201210_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AspectType',
            new_name='AspectModel',
        ),
        migrations.AddField(
            model_name='project',
            name='aspect_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.AspectModel'),
        ),
    ]
