# Generated by Django 3.0.8 on 2021-01-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_auto_20201214_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': 'date_created', 'verbose_name_plural': 'Data'},
        ),
    ]
