# Generated by Django 3.0.8 on 2021-01-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20210106_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
