# Generated by Django 3.0.8 on 2021-01-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aspect_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.AspectModel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='charts',
            field=models.ManyToManyField(blank=True, to='data.ChartType'),
        ),
    ]
