# Generated by Django 3.0.8 on 2021-01-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20210123_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
