# Generated by Django 3.0.8 on 2021-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20210221_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='relevance',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
