# Generated by Django 3.0.8 on 2021-03-10 19:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_data_relevance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='keywords',
        ),
        migrations.AddField(
            model_name='data',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
