# Generated by Django 3.0.8 on 2021-04-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_aspectdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectdefinition',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='aspectdefinition',
            unique_together={('rule_name', 'aspect_model')},
        ),
    ]
