# Generated by Django 3.0.8 on 2021-04-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20210409_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AspectDefinition',
            new_name='AspectRule',
        ),
    ]
