# Generated by Django 3.0.8 on 2021-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20210409_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectmodel',
            name='label',
            field=models.CharField(max_length=80),
        ),
    ]
