# Generated by Django 3.0.8 on 2021-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20210411_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('definition', models.TextField()),
                ('repustate_id', models.UUIDField()),
                ('language', models.CharField(default='en', max_length=2)),
                ('sentiment', models.CharField(max_length=80)),
                ('projects', models.ManyToManyField(to='data.Project')),
            ],
        ),
    ]
