# Generated by Django 3.0.8 on 2021-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='sentiment',
            field=models.ManyToManyField(to='data.Sentiment'),
        ),
    ]
