# Generated by Django 3.0.8 on 2021-04-27 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0052_auto_20210427_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
