# Generated by Django 3.0.8 on 2021-05-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_auto_20210506_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectrule',
            name='classifications',
        ),
        migrations.AddField(
            model_name='aspectmodel',
            name='classifications',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
