# Generated by Django 3.0.8 on 2021-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_auto_20210506_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectmodel',
            name='classifications',
        ),
        migrations.AddField(
            model_name='aspectrule',
            name='classifications',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
