# Generated by Django 3.0.8 on 2021-05-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_auto_20210508_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectmodel',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
