# Generated by Django 3.0.8 on 2021-05-29 16:07

from django.db import migrations, models

def set_language(apps, schema_editor):
    Data = apps.get_model('data', 'Data')
    for d in Data.objects.all():
        d.entities.update(language=d.language)

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_aspectmodel_standard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emotion',
        ),
        migrations.AddField(
            model_name='entity',
            name='english_label',
            field=models.CharField(db_index=True, default='', help_text='Non-blank only when language is not english', max_length=80),
        ),
        migrations.AddField(
            model_name='entity',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic (العربية)'), ('zh', 'Chinese (中文)'), ('da', 'Danish (Dansk)'), ('nl', 'Dutch (Nederlands)'), ('fi', 'Finnish (Suomi)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('he', 'Hebrew (עִברִית)'), ('it', 'Italian (Italiano)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('no', 'Norwegian (Norsk)'), ('pl', 'Polish (Polski)'), ('pt', 'Portuguese (Português)'), ('ru', 'Russian (русский)'), ('es', 'Spanish (Español)'), ('sv', 'Swedish (Svenska)'), ('tr', 'Turkish (Türk)'), ('th', 'Thai (ไทย)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('ur', 'Urdu (اردو)')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='sentiment',
            field=models.ManyToManyField(blank=True, to='data.Sentiment'),
        ),

        migrations.RunPython(set_language),
    ]
