# Generated by Django 3.0.8 on 2021-06-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_auto_20210529_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspectmodel',
            options={'ordering': ('label',)},
        ),
        migrations.AddField(
            model_name='alert',
            name='data',
            field=models.ManyToManyField(blank=True, to='data.Data'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic (العربية)'), ('zh', 'Chinese (中文)'), ('da', 'Danish (Dansk)'), ('nl', 'Dutch (Nederlands)'), ('fi', 'Finnish (Suomi)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('he', 'Hebrew (עִברִית)'), ('it', 'Italian (Italiano)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('no', 'Norwegian (Norsk)'), ('pl', 'Polish (Polski)'), ('pt', 'Portuguese (Português)'), ('ru', 'Russian (русский)'), ('es', 'Spanish (Español)'), ('sv', 'Swedish (Svenska)'), ('tr', 'Turkish (Türk)'), ('th', 'Thai (ไทย)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('ur', 'Urdu (اردو)')], default='en', max_length=2),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('frequency', models.IntegerField(default=0, help_text='How many times should the data appear before sending an alert')),
                ('keywords', models.TextField(blank=True)),
                ('emails', models.TextField(blank=True)),
                ('sms', models.TextField(blank=True)),
                ('aspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Aspect')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.AlertRule'),
        ),
    ]
