# Generated by Django 3.0.8 on 2021-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_auto_20210603_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=80),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='aspect',
            field=models.CharField(default='', max_length=80),
        ),
    ]
