# Generated by Django 3.0.8 on 2021-06-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_aspectmodel_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='handled',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='data',
        ),
        migrations.AddField(
            model_name='alert',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Data'),
        ),
    ]
