# Generated by Django 3.0.8 on 2021-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_auto_20210605_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('label', 'english_label', 'language')},
        ),
    ]
