# Generated by Django 3.0.8 on 2021-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_auto_20210608_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedAspectRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aspectrule',
            options={'ordering': ('rule_name',)},
        ),
        migrations.AlterField(
            model_name='aspectrule',
            name='classifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aspectrule',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
