# Generated by Django 3.0.8 on 2021-06-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_auto_20210608_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspectrule',
            options={'ordering': ('rule_name',)},
        ),
        migrations.AlterField(
            model_name='aspectrule',
            name='classifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aspectrule',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
