# Generated by Django 3.0.8 on 2021-06-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_auto_20210612_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredefinedAspectRules',
            new_name='PredefinedAspectRule',
        ),
    ]
