# Generated by Django 3.0.8 on 2021-06-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_auto_20210612_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedaspectrule',
            old_name='rule_name',
            new_name='label',
        ),
    ]
