# Generated by Django 3.0.8 on 2021-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_auto_20210612_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectrule',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
    ]
