# Generated by Django 3.0.8 on 2021-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_aspectrule_predefined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='weighted_score',
        ),
        migrations.AddField(
            model_name='alertrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
