# Generated by Django 3.0.8 on 2021-06-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_auto_20210615_2120'),
        ('data', '0066_auto_20210614_1448'),
    ]

    operations = [
    ]
