# Generated by Django 3.0.8 on 2021-06-20 21:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_merge_20210616_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='data',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
