# Generated by Django 3.0.8 on 2021-06-20 21:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_auto_20210620_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
