# Generated by Django 3.0.8 on 2021-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_auto_20210620_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_key',
            field=models.TextField(default=''),
        ),
    ]
