# Generated by Django 3.0.8 on 2021-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_sentiment_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectmodel',
            name='api_key',
            field=models.TextField(default=''),
        ),
    ]
