# Generated by Django 3.0.8 on 2021-06-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_aspectmodel_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='popup_text',
            field=models.TextField(blank=True, default='', help_text='Content for an initial popup. Markdown format supported'),
        ),
    ]
