# Generated by Django 3.0.8 on 2021-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_project_popup_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=models.CharField(default='', max_length=80),
        ),
    ]
