# Generated by Django 3.0.8 on 2021-06-27 21:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_auto_20210625_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
