# Generated by Django 3.0.8 on 2021-06-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_data_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
