# Generated by Django 3.0.8 on 2021-06-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_auto_20210627_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
