# Generated by Django 3.0.8 on 2021-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_auto_20210627_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='popup_title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
