# Generated by Django 3.0.8 on 2021-07-04 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0081_auto_20210627_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
