# Generated by Django 3.0.8 on 2021-07-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_project_popup_title'),
        ('data', '0083_auto_20210705_2259'),
    ]

    operations = [
    ]
