# Generated by Django 3.0.8 on 2021-07-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0084_merge_20210705_2318'),
        ('data', '0083_auto_20210707_0402'),
    ]

    operations = [
    ]
