# Generated by Django 3.0.8 on 2021-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_merge_20210707_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittersearch',
            name='entities',
        ),
        migrations.AlterField(
            model_name='twittersearch',
            name='aspect',
            field=models.ForeignKey(blank=True, default=None, help_text='Which aspect model to use? (optional)', limit_choices_to={'standard': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.AspectModel'),
        ),
    ]
