# Generated by Django 3.0.8 on 2021-07-13 22:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0086_auto_20210711_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
