# Generated by Django 3.0.8 on 2021-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_auto_20210716_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectmodel',
            name='managed',
            field=models.BooleanField(default=False, help_text='Does Repustate manage this model for them'),
        ),
        migrations.AlterField(
            model_name='aspectmodel',
            name='api_key',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='entity',
            name='api_key',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='api_key',
            field=models.CharField(max_length=80),
        ),
    ]
