# Generated by Django 3.0.8 on 2021-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_auto_20210716_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectrule',
            name='weight',
            field=models.IntegerField(default=5),
        ),
    ]
