# Generated by Django 3.0.8 on 2021-08-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_aspectrule_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=5)),
                ('aspect_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.AspectRule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
            options={
                'unique_together': {('project', 'aspect_rule')},
            },
        ),
    ]
