# Generated by Django 3.0.8 on 2021-07-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_exportcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcomments',
            name='source',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='data.Source'),
        ),
    ]
