# Generated by Django 3.0.8 on 2021-08-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0089_auto_20210814_2100'),
        ('data', '0090_aspectweight'),
    ]

    operations = [
    ]
