# Generated by Django 3.0.8 on 2021-08-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_merge_20210814_2108'),
        ('data', '0090_exportcomments_source'),
    ]

    operations = [
    ]
