# Generated by Django 3.0.8 on 2021-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_merge_20210819_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcomments',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportcomments',
            name='guid',
            field=models.CharField(max_length=128),
        ),
    ]
