# Generated by Django 3.0.8 on 2021-08-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_auto_20210819_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportcomments',
            options={'verbose_name_plural': 'Export Comments'},
        ),
        migrations.AddField(
            model_name='exportcomments',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Running'), (1, 'Running'), (2, 'Error'), (3, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='exportcomments',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
