# Generated by Django 3.0.8 on 2021-08-20 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_auto_20210819_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
