# Generated by Django 3.0.8 on 2021-09-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_auto_20210909_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('label', 'english_label', 'language', 'api_key')},
        ),
    ]
