nlp_phrase_lookup = {
    'Person.pro_athlete': 'athletes',
    'Org.political_party': 'political parties',
    'Technology.input_device': 'input device',
    'Person.criminal': 'criminals',
    'Location.hotel': 'hotels',
    'Person.us_president': 'US presidents',
    'Product.financial': 'financial products',
    'Health.antibody': 'antibodies',
    'Org.newspaper': 'newspapers',
    'Org.news_agency': 'news agencies',
    'Org.intelligence_agency': 'intelligence agencies',
    'Event.award': 'awards',
    'Time.day': 'days of the week',
    'Person.economist': 'economists',
    'Org.music_group': 'orchestras',
    'Animal.reptile': 'reptiles',
    'Event.genocide': 'genocides',
    'Person.government_employee': 'civil servants',
    'Product.smartwatch': 'smartwatch',
    'Person.fictional_character': 'fictional characters',
    'Org.pro_baseball_team': 'baseball teams',
    'Location.forest': 'forests',
    'Org.think_tank': 'think tanks',
    'Health.treatment': 'therapies',
    'Org.transit_system': 'transit systems',
    'Location.desert': 'deserts',
    'Org.hackers': 'hacker groups',
    'Event.trial': 'trials',
    'Product.fashion_accessory': 'fashion accessories',
    'Person.religious_founder': 'religious founders',
    'Location.waterfall': 'waterfalls',
    'Org.online_news': 'online publisher',
    'Science.planet': 'planets',
    'Health.bone': 'bones',
    'Event.legislation': 'legislation',
    'Person.surgeon': 'surgeons',
    'Org.college_sports_team': 'college sports teams',
    'Person.software_engineer': 'software engineers',
    'Product.pipeline_system': 'pipelines',
    'Product.automobile': 'cars',
    'Person.royalty': 'royalty',
    'Product.vehicle': 'vehicles',
    'Person.first_lady': 'First Ladies',
    'Org.radio_station': 'radio stations',
    'Location.prison': 'prisons',
    'Product.video_game': 'video games',
    'Org.broadcaster': 'TV networks',
    'Science.mineral': 'minerals',
    'Product.cpu': 'CPU',
    'Location.river': 'rivers',
    'Location.airport': 'airports',
    'Product.tea': 'teas',
    'Org.ideology': 'ideologies',
    'Health.trial': 'health trials',
    'Health.alternative_medicine': 'alternative medicine',
    'Number.economics': 'economic numbers',
    'Person.philosopher': 'philosophers',
    'Org.nonprofit': 'nonprofits',
    'Person.musician': 'musicians',
    'Person.music_group': 'music groups',
    'Org.business': 'businesses',
    'Org.business.industry': 'taxi companies',
    'Event.sport': 'sports',
    'Person.director': 'directors',
    'Health.symptom': 'symptoms',
    'Org.central_bank': 'central banks',
    'Product.digital_media_player': 'media players',
    'Event.social': 'social events',
    'Product.wine': 'wine',
    'Product.book': 'books',
    'Person.military_rank': 'military ranks',
    'Health.condition': 'disease',
    'Location.continent': 'continents',
    'Technology.software': 'software',
    'Person.sports_coach': 'coach',
    'Org.pro_soccer_team': 'soccer teams',
    'Event.crime': 'crimes',
    'Product.cleaning': 'cleaning products',
    'Location.lake': 'lakes',
    'Product.soft_drink': 'soft drinks',
    'Person.model': 'models',
    'Time.month': 'months',
    'Org.sports_league': 'leagues',
    'Product.cryptocurrency': 'crypto currencies',
    'Org.pro_rugby_team': 'rugby teams',
    'Health.peptide': 'peptides',
    'Event.activity': 'season activities',
    'Person.tv_presenter': 'TV presenter',
    'Animal.fish': 'fish',
    'Location.street': 'streets',
    'Product.smartphone': 'smartphones',
    'Science.chemical_element': 'chemical elements',
    'Location.island': 'islands',
    'Location.military_base': 'military bases',
    'Location.market': 'markets',
    'Number.financials': 'financial ratios',
    'Org.militants': 'militants',
    'Location.power_station': 'power stations',
    'Product.sex_toy': 'sex toys',
    'Technology.cpu_extensions': 'CPU extensions',
    'Product.personal_hygiene': 'sundry',
    'Product.musical_instrument': 'musical instrument',
    'Event.coup': 'political events',
    'Org.religion': 'religions',
    'Product.commodity': 'commodities',
    'Technology.file_format': 'file formats',
    'Event.trade_show': 'conferences',
    'Location.museum_or_gallery': 'museums',
    'Event.financial': 'financial events',
    'Science.particle': 'particles',
    'Technology.typeface': 'typefaces',
    'Person.religious_follower': 'religious followers',
    'Person.first_nations': 'First Nations',
    'Person.businessman': 'businessmen',
    'Person.scientist': 'scientists',
    'Event.war': 'war',
    'Product.podcast': 'podcasts',
    'Person.law_enforcement': 'law enforcement',
    'Event.weather': 'weather',
    'Location.mountain_range': 'mountain ranges',
    'Event.massacre': 'massacres',
    'Person.hacker': 'hackers',
    'Org.junior_hockey_team': 'junior hockey teams',
    'Person.world_leader': 'world leaders',
    'Person.computer_scientist': 'computer scientists',
    'Health.cell': 'cells',
    'Location.city': 'cities',
    'Location.building': 'buildings',
    'Person.author': 'authors',
    'Technology.component': 'hardware components',
    'Product.laptop': 'laptops',
    'Person.academic': 'academics',
    'Time.time_of_day': 'times of day',
    'Product.aircraft': 'aircraft',
    'Technology.software_development_process': 'software development processes',
    'Person.artist': 'artists',
    'Person.physician': 'physicians',
    'Technology.cpu_architecture': 'CPU architecture',
    'Person.emotion': 'emotions',
    'Location.state_or_province': 'states',
    'Person.broadcaster': 'broadcasters',
    'Person.poet': 'poets',
    'Person.nationality': 'nationalities',
    'Health.pharmaceutical': 'pharmaceuticals',
    'Person.relationship': 'family members',
    'Person.religious_figure': 'religious figures',
    'Location.statue': 'statues',
    'Org.stock_exchange': 'stock exchanges',
    'Event.us_constitution': 'ammendments',
    'Event.legal': 'legal events',
    'Org.medical': 'medical organizations',
    'Product.laundry_detergent': 'laundry detergents',
    'Location.canyon': 'canyon',
    'Health.muscle': 'muscles',
    'Animal.insect': 'insects',
    'Product.magazine': 'magazines',
    'Health.vitamin': 'vitamins',
    'Person.streamer': 'streamers',
    'Location.neighborhood': 'neighbourhoods',
    'Org.hospital': 'hospitals',
    'Product.coffee': 'coffees',
    'Technology.mobile_interface': 'mobile interfaces',
    'Org.trade_agreement': 'trade agreements',
    'Health.disorder': 'disorders',
    'Location.country': 'countries',
    'Event.military_operation': 'military operation',
    'Health.surgery': 'surgeries',
    'Time.season': 'seasons',
    'Org.government_committee': 'government committees',
    'Number.system': 'number systems',
    'Person.journalist': 'journalists',
    'Location.ward': 'wards',
    'Product.movie': 'movies',
    'Technology.operating_system': 'operating systems',
    'Health.organ': 'organs',
    'Person.playwright': 'playwrights',
    'Product.military_ship': 'military ships',
    'Location.convention_centre': 'convention centres',
    'Location.religious_site': 'religious site',
    'Number.number': 'numbers',
    'Location.train_station': 'train stations',
    'Product.tablet': 'tablets',
    'Product.clothing': 'clothing',
    'Technology.protocol': 'protocols',
    'Person.sports_position': 'sports positions',
    'Location.sea': 'seas',
    'Science.galaxy': 'galaxies',
    'Location.government_residence': 'government residences',
    'Location.university': 'universities',
    'Person.subculture': 'subcultures',
    'Product.album': 'albums',
    'Health.body_part': 'body parts',
    'Org.pro_football_team': 'arena football teams',
    'Health.enzyme': 'enzymes',
    'Person.judge': 'judges',
    'Event.motor_race': 'motor races',
    'Location.mountain': 'mountains',
    'Event.sporting_event': 'sporting event',
    'Science.chemical_compound': 'chemical compounds',
    'Time.holiday': 'holidays',
    'Location.borough': 'boroughs',
    'Event.political': 'political events',
    'Location.ocean': 'oceans',
    'Technology.social_network': 'social networks',
    'Org.pro_basketball_team': 'basketball teams',
    'Science.bacteria': 'bacteria',
    'Health.recreational_drug': 'recreational drugs',
    'Product.tv_episode': 'TV episode',
    'Person.activist': 'activists',
    'Product.jewellery': 'jewellery',
    'Product.music_genre': 'music genre',
    'Health.gene': 'genes',
    'Health.antigen': 'antigens',
    'Health.artery': 'arteries',
    'Product.weapon': 'weapons',
    'Health.tests': 'diagnostics',
    'Technology.infotainment': 'software',
    'Person.terrorist': 'terrorist',
    'Health.cancer': 'cancer',
    'Technology.streaming_service': 'streaming services',
    'Product.headphones': 'headphones',
    'Science.molecule': 'molecules',
    'Person.military_personnel': 'military personnel',
    'Product.registered_investment': 'registered investments',
    'Technology.programming_language': 'programming languages',
    'Location.transit_line': 'transit lines',
    'Person.politician': 'politicians',
    'Org.court': 'courts',
    'Science.star': 'stars',
    'Person.head_of_state_title': 'heads of state',
    'Org.labor_union': 'unions',
    'Person.whistleblower': 'whistleblowers',
    'Org.minor_league_baseball_team': 'minor league baseball teams',
    'Product.cargo_ship': 'cargo ships',
    'Event.pandemic': 'pandemics',
    'Event.festival': 'festivals',
    'Health.rate': 'health rates',
    'Org.empire': 'empires',
    'Person.astronaut': 'astronauts',
    'Product.manufacturing': 'manufacturing',
    'Product.beer': 'beers',
    'Location.city_area': 'city areas',
    'Product.currency': 'currencies',
    'Location.public_space': 'public spaces',
    'Animal.amphibian': 'amphibians',
    'Person.actor': 'actors',
    'Product.food': 'food',
    'Location.county': 'counties',
    'Location.direction': 'directions',
    'Person.radio_host': 'radio host',
    'Person.language': 'languages',
    'Event.airplane_crash': 'airplane crashes',
    'Animal.bird': 'birds',
    'Technology.software_license': 'software licenses',
    'Science.isotope': 'isotopes',
    'Person.comedian': 'comedians',
    'Person.ethnicity': 'ethnicities',
    'Person.lawyer': 'lawyers',
    'Location.region': 'regions',
    'Location.park': 'parks',
    'Product.tv_show': 'TV shows',
    'Number.math_constant': 'mathematical constants',
    'Animal.mammal': 'mammals',
    'Org.government_legislature': 'legislatures',
    'Technology.network': 'networks',
    'Org.pro_hockey_team': 'hockey teams',
    'Person.philanthropist': 'philanthropists',
    'Science.plant': 'plants',
    'Event.terrorist_attack': 'terrorist attack',
    'Org.government_agency': 'government agencies',
    'Product.video_game_console': 'video game consoles',
    'Location.stadium': 'stadiums',
    'Location.bridge': 'bridges',
    'Org.transit_authority': 'transit authorities',
    'Number.taxes': 'taxes',
    'Location.highway': 'highways',
    'Technology.algorithm': 'algorithms',
    'Event.time_management': 'time management',
}
