# Generated by Django 3.0.8 on 2021-06-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('value', models.CharField(blank=True, max_length=80)),
                ('upload', models.FileField(max_length=80, upload_to='customize/')),
            ],
        ),
    ]
