# Generated by Django 3.0.8 on 2021-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='upload',
            field=models.FileField(blank=True, max_length=80, upload_to='customize/'),
        ),
    ]
