from data.models import *

rules = [
    ("airline", "inflight"),
    ("airline", "loyalty"),
    ("airline", "price"),
    ("airline", "staff"),
    ("banking", "bank"),
    ("banking", "branch"),
    ("banking", "price"),
    ("banking", "products"),
    ("banking", "service"),
    ("banking", "staff"),
    ("banking", "technology"),
    ("banking", "transaction"),
    ("hotel", "accommodations"),
    ("hotel", "amenities"),
    ("hotel", "attractions"),
    ("hotel", "bathroom"),
    ("hotel", "beds"),
    ("hotel", "business-amenities"),
    ("hotel", "cleanliness"),
    ("hotel", "customers"),
    ("hotel", "food"),
    ("hotel", "furniture"),
    ("hotel", "hosts"),
    ("hotel", "internet"),
    ("hotel", "location"),
    ("hotel", "meal"),
    ("hotel", "noise"),
    ("hotel", "odor"),
    ("hotel", "parking"),
    ("hotel", "pests"),
    ("hotel", "pets"),
    ("hotel", "pool"),
    ("hotel", "price"),
    ("hotel", "recommendation"),
    ("hotel", "safety"),
    ("hotel", "schedule"),
    ("hotel", "staff"),
    ("hotel", "tripstyle"),
    ("restaurant", "action"),
    ("restaurant", "atmosphere"),
    ("restaurant", "events"),
    ("restaurant", "experience"),
    ("restaurant", "food"),
    ("restaurant", "intent"),
    ("restaurant", "location"),
    ("restaurant", "parking"),
    ("restaurant", "price"),
    ("restaurant", "reservations"),
    ("restaurant", "service"),
    ("restaurant", "staff"),
    ("restaurant", "technology"),
    ("retail", "action"),
    ("retail", "fitting_rooms"),
    ("retail", "intent"),
    ("retail", "jobs"),
    ("retail", "product"),
    ("retail", "service"),
    ("retail", "staff"),
    ("retail", "store_experience"),
    ("retail", "value"),
    ("telecom", "price"),
    ("telecom", "product"),
    ("telecom", "service"),
    ("telecom", "staff"),
    ("voice_of_employee", "colleagues"),
    ("voice_of_employee", "communication"),
    ("voice_of_employee", "job security"),
    ("voice_of_employee", "management"),
    ("voice_of_employee", "organization"),
    ("voice_of_employee", "performance"),
    ("voice_of_employee", "product & technology"),
    ("voice_of_employee", "promotion & career"),
    ("voice_of_employee", "recruitment & on-boarding"),
    ("voice_of_employee", "salary & incentive"),
    ("voice_of_employee", "support & appreciation"),
    ("voice_of_employee", "vacation"),
    ("voice_of_employee", "work from home"),
    ("voice_of_employee", "workload"),
]

def run():
    for mode, rule in rules:
        AspectRule.objects.get_or_create(rule_name=rule, aspect_model=AspectModel.objects.get(label=model))
